apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  source:
    helm:
      version: v3
      valueFiles:
      - ../values-gke.andersondario.dev.yaml
    path: argocd-install/argo-cd
    repoURL: https://github.com/andersondario/argocd-gitops.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appprojects
  namespace: argocd
spec:
  project: argocd
  source:
    path: argocd-appprojects
    repoURL: https://github.com/andersondario/argocd-gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  project: argocd
  source:
    path: argocd-applications
    repoURL: https://github.com/andersondario/argocd-gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress-nginx
  namespace: argocd
spec:
  project: argocd
  source:
    helm:
      version: v3
      parameters:
        - name: controller.extraArgs.enable-ssl-passthrough
          value: ""
        - name: controller.admissionWebhooks.enabled
          value: "false"
    path: argocd-install/ingress-nginx
    repoURL: https://github.com/andersondario/argocd-gitops.git
    targetRevision: HEAD
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
